### PR TITLE
Fixed the -lh flag not working and executable files have icons with a green color.

### PR DESCRIPTION
**Pull request by elbachir-one**
The -lh flag is there but not working, now it does work.

### CODE REVIEW

**Comment by elbachir-one** [comment]
The -lh flag was not working, now it should work fine.
Executable files have icons with a green color.

**Review by Tigermen0710 — APPROVED** [review]

**Comment by Tigermen0710** [comment]
ok, thank you!

**Comment by Tigermen0710** [comment]
image
can you please stop moving directory icon to left

**Comment by elbachir-one** [comment]
That is just my editor config.

**Comment by elbachir-one** [comment]
I think the icon for directories should be on the right.

image

It does mess up the alignment.

image

**Pull request merged**
